// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: MASHARE

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_nowifi
void ui_nowifi_screen_init(void);
lv_obj_t *ui_nowifi;
lv_obj_t *ui_WIFIKEYBOARD;
lv_obj_t *ui_SSID;
lv_obj_t *ui_PASSWORD;
lv_obj_t *ui_SSIDLABEL;
lv_obj_t *ui_PASSWORDLABEL;
lv_obj_t *ui_CONNECTBUTTON;

// SCREEN: ui_home
void ui_home_screen_init(void);
lv_obj_t *ui_home;
lv_obj_t *ui_WeatherPanel;
lv_obj_t *ui_DATELABEL;
lv_obj_t *ui_CONDITIONLABEL;
lv_obj_t *ui_TIMELABEL;
lv_obj_t *ui_WEATHERICON;
lv_obj_t *ui_PlantWaterPanel;
lv_obj_t *ui_PLANT1LABEL;
lv_obj_t *ui_PLANT2LABEL;
lv_obj_t *ui_PLANT3LABEL;
lv_obj_t *ui_PLANT4LABEL;
lv_obj_t *ui_PLANT1BAR;
lv_obj_t *ui_PLANT2BAR;
lv_obj_t *ui_PLANT3BAR;
lv_obj_t *ui_PLANT4BAR;
lv_obj_t *ui_PLANTICON;
lv_obj_t *ui_PLANTICON1;
lv_obj_t *ui_PLANTICON2;
lv_obj_t *ui_PLANTICON3;
lv_obj_t *ui_TempPanel;
lv_obj_t *ui_BEDROOMLABEL;
lv_obj_t *ui_LIVINGROOMLABEL;
lv_obj_t *ui_DOGFOODLABEL;
lv_obj_t *ui_LRTEMPBAR;
lv_obj_t *ui_LRHUMBAR;
lv_obj_t *ui_DFLEVELBAR;
lv_obj_t *ui_BRHUMBAR;
lv_obj_t *ui_BRTEMPBAR;
lv_obj_t *ui_DOGICON;
lv_obj_t *ui_TEMPICON;
lv_obj_t *ui_HUMIDICON;
lv_obj_t *ui_TEMPICON1;
lv_obj_t *ui_HUMIDICON1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_309644606[1] = {&ui_img_1288332288};
const lv_img_dsc_t *ui_imgset_47804335[1] = {&ui_img_1276940811};
const lv_img_dsc_t *ui_imgset_1604130866[1] = {&ui_img_1991736760};
const lv_img_dsc_t *ui_imgset_174428635[1] = {&ui_img_1503224665};
const lv_img_dsc_t *ui_imgset_107484460[1] = {&ui_img_1336096536};
const lv_img_dsc_t *ui_imgset_789732520[1] = {&ui_img_1313047014};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_nowifi_screen_init();
ui_home_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr(ui_home);
}
