// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: MASHARE

#include "ui.h"

void ui_home_screen_init(void)
{
ui_home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_home, lv_color_hex(0x4383B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeatherPanel = lv_obj_create(ui_home);
lv_obj_set_width( ui_WeatherPanel, 395);
lv_obj_set_height( ui_WeatherPanel, 208);
lv_obj_set_x( ui_WeatherPanel, -190 );
lv_obj_set_y( ui_WeatherPanel, -120 );
lv_obj_set_align( ui_WeatherPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_WeatherPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DATELABEL = lv_label_create(ui_WeatherPanel);
lv_obj_set_width( ui_DATELABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DATELABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DATELABEL, 0 );
lv_obj_set_y( ui_DATELABEL, -70 );
lv_obj_set_align( ui_DATELABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_DATELABEL,"DATE");
lv_obj_set_style_text_font(ui_DATELABEL, &ui_font_LEMONMILK26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CONDITIONLABEL = lv_label_create(ui_WeatherPanel);
lv_obj_set_width( ui_CONDITIONLABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CONDITIONLABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CONDITIONLABEL, 99 );
lv_obj_set_y( ui_CONDITIONLABEL, 66 );
lv_obj_set_align( ui_CONDITIONLABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_CONDITIONLABEL,"WEATHER \nCONDITION");
lv_obj_set_style_text_font(ui_CONDITIONLABEL, &ui_font_LEMONMILK26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_label_set_long_mode(ui_CONDITIONLABEL, LV_LABEL_LONG_WRAP);

ui_TIMELABEL = lv_label_create(ui_WeatherPanel);
lv_obj_set_width( ui_TIMELABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TIMELABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TIMELABEL, 120 );
lv_obj_set_y( ui_TIMELABEL, -70 );
lv_obj_set_align( ui_TIMELABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_TIMELABEL,"TIME");
lv_obj_set_style_text_font(ui_TIMELABEL, &ui_font_LEMONMILK26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_label_set_long_mode(ui_TIMELABEL, LV_LABEL_LONG_WRAP);

ui_WEATHERICON = lv_img_create(ui_WeatherPanel);
lv_img_set_src(ui_WEATHERICON, &ui_img_1336096536);
lv_obj_set_width( ui_WEATHERICON, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_WEATHERICON, LV_SIZE_CONTENT);   /// 75
lv_obj_set_x( ui_WEATHERICON, -100 );
lv_obj_set_y( ui_WEATHERICON, 0 );
lv_obj_set_align( ui_WEATHERICON, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WEATHERICON, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WEATHERICON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PlantWaterPanel = lv_obj_create(ui_home);
lv_obj_set_width( ui_PlantWaterPanel, 365);
lv_obj_set_height( ui_PlantWaterPanel, 450);
lv_obj_set_x( ui_PlantWaterPanel, 205 );
lv_obj_set_y( ui_PlantWaterPanel, 0 );
lv_obj_set_align( ui_PlantWaterPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PlantWaterPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PLANT1LABEL = lv_label_create(ui_PlantWaterPanel);
lv_obj_set_width( ui_PLANT1LABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANT1LABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANT1LABEL, -114 );
lv_obj_set_y( ui_PLANT1LABEL, -199 );
lv_obj_set_align( ui_PLANT1LABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_PLANT1LABEL,"PLANT1");
lv_obj_set_style_text_font(ui_PLANT1LABEL, &ui_font_Heavitas26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PLANT2LABEL = lv_label_create(ui_PlantWaterPanel);
lv_obj_set_width( ui_PLANT2LABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANT2LABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANT2LABEL, -114 );
lv_obj_set_y( ui_PLANT2LABEL, -96 );
lv_obj_set_align( ui_PLANT2LABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_PLANT2LABEL,"PLANT2");
lv_obj_set_style_text_font(ui_PLANT2LABEL, &ui_font_Heavitas26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PLANT3LABEL = lv_label_create(ui_PlantWaterPanel);
lv_obj_set_width( ui_PLANT3LABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANT3LABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANT3LABEL, -114 );
lv_obj_set_y( ui_PLANT3LABEL, 4 );
lv_obj_set_align( ui_PLANT3LABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_PLANT3LABEL,"PLANT3");
lv_obj_set_style_text_font(ui_PLANT3LABEL, &ui_font_Heavitas26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PLANT4LABEL = lv_label_create(ui_PlantWaterPanel);
lv_obj_set_width( ui_PLANT4LABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANT4LABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANT4LABEL, -114 );
lv_obj_set_y( ui_PLANT4LABEL, 104 );
lv_obj_set_align( ui_PLANT4LABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_PLANT4LABEL,"PLANT4");
lv_obj_set_style_text_font(ui_PLANT4LABEL, &ui_font_Heavitas26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PLANT1BAR = lv_bar_create(ui_PlantWaterPanel);
lv_bar_set_value(ui_PLANT1BAR,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_PLANT1BAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_PLANT1BAR, 335);
lv_obj_set_height( ui_PLANT1BAR, 37);
lv_obj_set_x( ui_PLANT1BAR, 0 );
lv_obj_set_y( ui_PLANT1BAR, -150 );
lv_obj_set_align( ui_PLANT1BAR, LV_ALIGN_CENTER );

ui_PLANT2BAR = lv_bar_create(ui_PlantWaterPanel);
lv_bar_set_value(ui_PLANT2BAR,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_PLANT2BAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_PLANT2BAR, 335);
lv_obj_set_height( ui_PLANT2BAR, 37);
lv_obj_set_x( ui_PLANT2BAR, 0 );
lv_obj_set_y( ui_PLANT2BAR, -47 );
lv_obj_set_align( ui_PLANT2BAR, LV_ALIGN_CENTER );

ui_PLANT3BAR = lv_bar_create(ui_PlantWaterPanel);
lv_bar_set_value(ui_PLANT3BAR,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_PLANT3BAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_PLANT3BAR, 335);
lv_obj_set_height( ui_PLANT3BAR, 37);
lv_obj_set_x( ui_PLANT3BAR, 0 );
lv_obj_set_y( ui_PLANT3BAR, 56 );
lv_obj_set_align( ui_PLANT3BAR, LV_ALIGN_CENTER );

ui_PLANT4BAR = lv_bar_create(ui_PlantWaterPanel);
lv_bar_set_value(ui_PLANT4BAR,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_PLANT4BAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_PLANT4BAR, 335);
lv_obj_set_height( ui_PLANT4BAR, 37);
lv_obj_set_x( ui_PLANT4BAR, 0 );
lv_obj_set_y( ui_PLANT4BAR, 159 );
lv_obj_set_align( ui_PLANT4BAR, LV_ALIGN_CENTER );

ui_PLANTICON = lv_img_create(ui_PlantWaterPanel);
lv_img_set_src(ui_PLANTICON, &ui_img_1503224665);
lv_obj_set_width( ui_PLANTICON, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANTICON, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANTICON, lv_pct(-12) );
lv_obj_set_y( ui_PLANTICON, lv_pct(-50) );
lv_obj_set_align( ui_PLANTICON, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PLANTICON, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PLANTICON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PLANTICON1 = lv_img_create(ui_PlantWaterPanel);
lv_img_set_src(ui_PLANTICON1, &ui_img_1503224665);
lv_obj_set_width( ui_PLANTICON1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANTICON1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANTICON1, lv_pct(-12) );
lv_obj_set_y( ui_PLANTICON1, lv_pct(-25) );
lv_obj_set_align( ui_PLANTICON1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PLANTICON1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PLANTICON1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PLANTICON2 = lv_img_create(ui_PlantWaterPanel);
lv_img_set_src(ui_PLANTICON2, &ui_img_1503224665);
lv_obj_set_width( ui_PLANTICON2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANTICON2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANTICON2, lv_pct(-12) );
lv_obj_set_y( ui_PLANTICON2, lv_pct(0) );
lv_obj_set_align( ui_PLANTICON2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PLANTICON2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PLANTICON2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PLANTICON3 = lv_img_create(ui_PlantWaterPanel);
lv_img_set_src(ui_PLANTICON3, &ui_img_1503224665);
lv_obj_set_width( ui_PLANTICON3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PLANTICON3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PLANTICON3, lv_pct(-12) );
lv_obj_set_y( ui_PLANTICON3, lv_pct(25) );
lv_obj_set_align( ui_PLANTICON3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PLANTICON3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PLANTICON3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempPanel = lv_obj_create(ui_home);
lv_obj_set_width( ui_TempPanel, 395);
lv_obj_set_height( ui_TempPanel, 226);
lv_obj_set_x( ui_TempPanel, -190 );
lv_obj_set_y( ui_TempPanel, 112 );
lv_obj_set_align( ui_TempPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BEDROOMLABEL = lv_label_create(ui_TempPanel);
lv_obj_set_width( ui_BEDROOMLABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BEDROOMLABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BEDROOMLABEL, 110 );
lv_obj_set_y( ui_BEDROOMLABEL, -80 );
lv_obj_set_align( ui_BEDROOMLABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_BEDROOMLABEL,"BEDROOM");
lv_obj_set_style_text_font(ui_BEDROOMLABEL, &ui_font_BebasNeue24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LIVINGROOMLABEL = lv_label_create(ui_TempPanel);
lv_obj_set_width( ui_LIVINGROOMLABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LIVINGROOMLABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LIVINGROOMLABEL, 20 );
lv_obj_set_y( ui_LIVINGROOMLABEL, -160 );
lv_obj_set_align( ui_LIVINGROOMLABEL, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_LIVINGROOMLABEL,"Living Room");
lv_obj_set_style_text_font(ui_LIVINGROOMLABEL, &ui_font_BebasNeue24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DOGFOODLABEL = lv_label_create(ui_TempPanel);
lv_obj_set_width( ui_DOGFOODLABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DOGFOODLABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DOGFOODLABEL, lv_pct(0) );
lv_obj_set_y( ui_DOGFOODLABEL, lv_pct(15) );
lv_obj_set_align( ui_DOGFOODLABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_DOGFOODLABEL,"DOG FOOD");
lv_obj_set_style_text_font(ui_DOGFOODLABEL, &ui_font_BebasNeue24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LRTEMPBAR = lv_bar_create(ui_TempPanel);
lv_bar_set_mode(ui_LRTEMPBAR, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_LRTEMPBAR, 30,110);
lv_bar_set_value(ui_LRTEMPBAR,70,LV_ANIM_OFF);
lv_bar_set_start_value(ui_LRTEMPBAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LRTEMPBAR, 150);
lv_obj_set_height( ui_LRTEMPBAR, 10);
lv_obj_set_x( ui_LRTEMPBAR, -94 );
lv_obj_set_y( ui_LRTEMPBAR, -48 );
lv_obj_set_align( ui_LRTEMPBAR, LV_ALIGN_CENTER );
lv_bar_set_range(ui_LRTEMPBAR, 33, 110);

ui_LRHUMBAR = lv_bar_create(ui_TempPanel);
lv_bar_set_mode(ui_LRHUMBAR, LV_BAR_MODE_RANGE);
lv_bar_set_value(ui_LRHUMBAR,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_LRHUMBAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LRHUMBAR, 150);
lv_obj_set_height( ui_LRHUMBAR, 10);
lv_obj_set_x( ui_LRHUMBAR, -94 );
lv_obj_set_y( ui_LRHUMBAR, -19 );
lv_obj_set_align( ui_LRHUMBAR, LV_ALIGN_CENTER );
lv_bar_set_range(ui_LRHUMBAR, 0, 100);

ui_DFLEVELBAR = lv_bar_create(ui_TempPanel);
lv_bar_set_value(ui_DFLEVELBAR,4.175,LV_ANIM_OFF);
lv_bar_set_start_value(ui_DFLEVELBAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_DFLEVELBAR, 330);
lv_obj_set_height( ui_DFLEVELBAR, 50);
lv_obj_set_x( ui_DFLEVELBAR, 20 );
lv_obj_set_y( ui_DFLEVELBAR, 75 );
lv_obj_set_align( ui_DFLEVELBAR, LV_ALIGN_CENTER );
lv_bar_set_range(ui_DFLEVELBAR, 0, 8.25);

ui_BRHUMBAR = lv_bar_create(ui_TempPanel);
lv_bar_set_mode(ui_BRHUMBAR, LV_BAR_MODE_RANGE);
lv_bar_set_value(ui_BRHUMBAR,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BRHUMBAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BRHUMBAR, 150);
lv_obj_set_height( ui_BRHUMBAR, 10);
lv_obj_set_x( ui_BRHUMBAR, 105 );
lv_obj_set_y( ui_BRHUMBAR, -20 );
lv_obj_set_align( ui_BRHUMBAR, LV_ALIGN_CENTER );
lv_bar_set_range(ui_BRHUMBAR, 0, 100);

ui_BRTEMPBAR = lv_bar_create(ui_TempPanel);
lv_bar_set_mode(ui_BRTEMPBAR, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_BRTEMPBAR, 30,110);
lv_bar_set_value(ui_BRTEMPBAR,70,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BRTEMPBAR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BRTEMPBAR, 150);
lv_obj_set_height( ui_BRTEMPBAR, 10);
lv_obj_set_x( ui_BRTEMPBAR, 105 );
lv_obj_set_y( ui_BRTEMPBAR, -48 );
lv_obj_set_align( ui_BRTEMPBAR, LV_ALIGN_CENTER );
lv_bar_set_range(ui_LRTEMPBAR, 33, 110);

ui_DOGICON = lv_img_create(ui_TempPanel);
lv_img_set_src(ui_DOGICON, &ui_img_1288332288);
lv_obj_set_width( ui_DOGICON, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_DOGICON, LV_SIZE_CONTENT);   /// 75
lv_obj_set_x( ui_DOGICON, -170 );
lv_obj_set_y( ui_DOGICON, 77 );
lv_obj_set_align( ui_DOGICON, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DOGICON, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DOGICON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TEMPICON = lv_img_create(ui_TempPanel);
lv_img_set_src(ui_TEMPICON, &ui_img_1313047014);
lv_obj_set_width( ui_TEMPICON, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_TEMPICON, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_TEMPICON, lv_pct(-53) );
lv_obj_set_y( ui_TEMPICON, lv_pct(-27) );
lv_obj_set_align( ui_TEMPICON, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TEMPICON, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TEMPICON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HUMIDICON = lv_img_create(ui_TempPanel);
lv_img_set_src(ui_HUMIDICON, &ui_img_1991736760);
lv_obj_set_width( ui_HUMIDICON, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_HUMIDICON, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_HUMIDICON, lv_pct(-52) );
lv_obj_set_y( ui_HUMIDICON, lv_pct(-11) );
lv_obj_set_align( ui_HUMIDICON, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HUMIDICON, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HUMIDICON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TEMPICON1 = lv_img_create(ui_TempPanel);
lv_img_set_src(ui_TEMPICON1, &ui_img_1313047014);
lv_obj_set_width( ui_TEMPICON1, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_TEMPICON1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_TEMPICON1, lv_pct(3) );
lv_obj_set_y( ui_TEMPICON1, lv_pct(-27) );
lv_obj_set_align( ui_TEMPICON1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TEMPICON1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TEMPICON1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HUMIDICON1 = lv_img_create(ui_TempPanel);
lv_img_set_src(ui_HUMIDICON1, &ui_img_1991736760);
lv_obj_set_width( ui_HUMIDICON1, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_HUMIDICON1, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_HUMIDICON1, lv_pct(4) );
lv_obj_set_y( ui_HUMIDICON1, lv_pct(-11) );
lv_obj_set_align( ui_HUMIDICON1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HUMIDICON1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HUMIDICON1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
