// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: MASHARE

#include "ui.h"

void ui_nowifi_screen_init(void)
{
    ui_nowifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_nowifi, LV_OBJ_FLAG_SCROLLABLE);    // Flags
    lv_obj_set_style_bg_color(ui_nowifi, lv_color_hex(0x4383B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIKEYBOARD = lv_keyboard_create(ui_nowifi);
    lv_obj_set_width(ui_WIFIKEYBOARD, 800);
    lv_obj_set_height(ui_WIFIKEYBOARD, 240);
    lv_obj_set_x(ui_WIFIKEYBOARD, 0);
    lv_obj_set_y(ui_WIFIKEYBOARD, 120);
    lv_obj_set_align(ui_WIFIKEYBOARD, LV_ALIGN_CENTER);

    ui_SSID = lv_textarea_create(ui_nowifi);
    lv_obj_set_width(ui_SSID, 420);
    lv_obj_set_height(ui_SSID, 45);
    lv_obj_set_x(ui_SSID, 0);
    lv_obj_set_y(ui_SSID, -160);
    lv_obj_set_align(ui_SSID, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SSID, "WIFI-SSID");

    ui_PASSWORD = lv_textarea_create(ui_nowifi);
    lv_obj_set_width(ui_PASSWORD, 420);
    lv_obj_set_height(ui_PASSWORD, 45);
    lv_obj_set_x(ui_PASSWORD, 0);
    lv_obj_set_y(ui_PASSWORD, -80);
    lv_obj_set_align(ui_PASSWORD, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PASSWORD, "WIFI-PASSWORD");

    ui_SSIDLABEL = lv_label_create(ui_nowifi);
    lv_obj_set_width(ui_SSIDLABEL, LV_SIZE_CONTENT);  // 1
    lv_obj_set_height(ui_SSIDLABEL, LV_SIZE_CONTENT);   // 1
    lv_obj_set_x(ui_SSIDLABEL, -183);
    lv_obj_set_y(ui_SSIDLABEL, -195);
    lv_obj_set_align(ui_SSIDLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLABEL, "SSID:");
    lv_obj_set_style_text_color(ui_SSIDLABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSIDLABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSIDLABEL, &ui_font_BebasNeue24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PASSWORDLABEL = lv_label_create(ui_nowifi);
    lv_obj_set_width(ui_PASSWORDLABEL, LV_SIZE_CONTENT);  // 1
    lv_obj_set_height(ui_PASSWORDLABEL, LV_SIZE_CONTENT);   // 1
    lv_obj_set_x(ui_PASSWORDLABEL, -160);
    lv_obj_set_y(ui_PASSWORDLABEL, -115);
    lv_obj_set_align(ui_PASSWORDLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PASSWORDLABEL, "PASSWORD:");
    lv_obj_set_style_text_color(ui_PASSWORDLABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PASSWORDLABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PASSWORDLABEL, &ui_font_BebasNeue24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create the Connect button
    ui_CONNECTBUTTON = lv_btn_create(ui_nowifi);
    lv_obj_set_width(ui_CONNECTBUTTON, 120);
    lv_obj_set_height(ui_CONNECTBUTTON, 50);
    lv_obj_set_x(ui_CONNECTBUTTON, 300);
    lv_obj_set_y(ui_CONNECTBUTTON, -120);
    lv_obj_set_align(ui_CONNECTBUTTON, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CONNECTBUTTON, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONNECTBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * label = lv_label_create(ui_CONNECTBUTTON);
    lv_label_set_text(label, "Connect");
    lv_obj_center(label);

    lv_keyboard_set_textarea(ui_WIFIKEYBOARD, ui_PASSWORD);
}
